### ISSUE TITLE
Rodar

### ISSUE THREAD

**Issue by SeuRonao** [robertolima301/projeto-python-pesquisa-arquivo-de-texto-p-datas-formatadas#1]
O código do jeito que ele está no main não chega a rodar.

Existem vários erros de sintaxe no código.

**Comment by robertolima301** [comment]
OK professor obrigado pelo feddback fiz umas alterações acho que agora dá
certo obrigado!

Ronan Soares ***@***.***> escreveu no dia terça, 18/10/2022
à(s) 16:28:

**Comment by SeuRonao** [comment]
Continua com erros de sintaxe.
Não imagino como você está rodando isso em qualquer que seja o interpretador python.
Consegue bater um screenshot do resultado desse programa rodando?

**Comment by robertolima301** [comment]
Poxa tô pelo Vscode, deve ser alguma coisa? eu vou verificar o código
novamente no github ok.


Ronan Soares ***@***.***> escreveu no dia terça, 18/10/2022
à(s) 17:15:

**Comment by robertolima301** [comment]
kkk eu acho q descobri uma coisa bem engraçada eu coloquei a tradução do
navegador em Português e por isso ficava dando erro de interpretação em
inglês agora deixei normal em inglês ás  vezes isso acontece por conta da
tradução simultânea acredito q agora dê certo peço desculpas por isso!

Roberto Lima ***@***.***> escreveu no dia terça, 18/10/2022
à(s) 17:28:

**Comment by SeuRonao** [comment]
Pelo próprio vscode você consegue fazer os commits, basta instalar o git.
Se quiser evitar ficar copiando e colando o código.
Sugiro fazer isso que continua com erro de sintaxe.
O que aparece aqui no GitHub.

**Comment by robertolima301** [comment]
Ok.

Ronan Soares ***@***.***> escreveu no dia terça, 18/10/2022
à(s) 17:49:
